### PR TITLE
Stm32f brd bringup

### PR DESCRIPTION
**Pull request by rspolyak**
Bring up of custom STM32F103 dev board

### CODE REVIEW

**Review by garyachy — COMMENTED** [review]
Do you use this board (http://www.kosmodrom.com.ua/el.php?name=STM32F103C8T6-MODUL) ? I want to order one for myself.

**Review by garyachy — COMMENTED** [review]
It is not clear for me why you copy files from Chibios? Have you modified them?

**Comment by rspolyak** [comment]
- The board is the same. It can be ordered also from diylab.
- These files are unique for this board. Non of supported ChibiOS boards cna be reused. What exact file are you concerned with?

**Review by yhreshko — APPROVED** [review]

**Comment by yhreshko** [comment]
Should I merge?

**Pull request merged**
